// Generated by https://quicktype.io

export type LoginData = {
  correo: string;
  password: string;
};

export type RegisterData = {
  correo: string;
  password: string;
  nombre: string;
};

export type LoginResponse = {
  usuario: Usuario;
  token: string;
};

export type Usuario = {
  rol: string;
  estado: boolean;
  google: boolean;
  nombre: string;
  correo: string;
  uid: string;
  img?: string;
};

// Products

// Generated by https://quicktype.io

export type ProductsResponse = {
  total: number;
  productos: Producto[];
};

export type Producto = {
  precio: number;
  _id: string;
  nombre: string;
  categoria: Categoria;
  usuario: Categoria;
  img?: string;
};

// Generated by https://quicktype.io

export type CategoriesResponse = {
  total: number;
  categorias: Categoria[];
};

export type Categoria = {
  _id: string;
  nombre: string;
  usuario?: CreatedBy;
};

export type CreatedBy = {
  _id: string;
  nombre: string;
};
